"use client";

import React, { createContext, useCallback, useContext, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ExpenseCategory, PaymentMethod, VehicleAcquisitionType, VehicleStatus } from "@prisma/client";

export interface VehicleExpenseItem { id: string; vehicleId: string; category: ExpenseCategory; description: string; partsCost: number; laborCost: number; amount: number; expenseDate: string; supplierName?: string; }
export interface VehicleItem { id: string; garageId: string; plate: string; vin: string; renavam: string; brand: string; model: string; version: string; yearManufacture: number; yearModel: number; color: string; mileageCurrent: number; status: VehicleStatus; acquisitionType: VehicleAcquisitionType; acquisitionDate: string; acquisitionPrice: number; fipeCode?: string; fipePriceAtAcquisition?: number; fipeReferenceMonth?: string; targetSalePrice?: number; minimumSalePrice?: number; notes?: string; expenses: VehicleExpenseItem[]; totalPartsCost: number; totalLaborCost: number; totalOtherCost: number; totalExpensesCost: number; totalAccumulatedCost: number; }
export interface GeneralExpenseItem { id: string; garageId: string; category: string; description: string; amount: number; dueDate: string; isRecurring: boolean; isPaid: boolean; }
export interface SaleItem { id: string; garageId: string; vehicleId: string; vehicleName: string; plate: string; customerName: string; saleDate: string; finalSalePrice: number; paymentMethod: PaymentMethod; totalAccumulatedCost: number; grossProfit: number; netProfit: number; hasTradeIn: boolean; tradeInVehiclePlate?: string; }
export interface GarageInfo { id: string; name: string; slug: string; documentCnpjCpf: string; role: string; }

type SaleInput = { customerName: string; customerDocument: string; customerPhone: string; finalSalePrice: number; paymentMethod: PaymentMethod; salesCommission?: number; notes?: string; tradeIn?: { brand: string; model: string; version: string; yearManufacture: number; yearModel: number; plate: string; color: string; mileage: number; agreedValue: number } };
interface GarageContextType { garage: GarageInfo; availableGarages: GarageInfo[]; vehicles: VehicleItem[]; generalExpenses: GeneralExpenseItem[]; sales: SaleItem[]; loading: boolean; error: string | null; switchGarage: (slug: string) => void; refresh: () => Promise<void>; addVehicle: (data: Partial<VehicleItem>) => Promise<VehicleItem>; addVehicleExpense: (vehicleId: string, data: { category: ExpenseCategory; description: string; partsCost: number; laborCost: number; otherCost?: number; supplierName?: string }) => Promise<void>; updateVehicleStatus: (vehicleId: string, newStatus: VehicleStatus, notes?: string) => Promise<void>; sellVehicle: (vehicleId: string, saleData: SaleInput) => Promise<void>; addGeneralExpense: (data: Omit<GeneralExpenseItem, "id" | "garageId" | "isPaid">) => Promise<void>; }

const EMPTY_GARAGE: GarageInfo = { id: "", name: "Carregando…", slug: "", documentCnpjCpf: "", role: "" };
const GarageContext = createContext<GarageContextType | undefined>(undefined);
const asNumber = (value: unknown) => Number(value || 0);
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || "Falha ao comunicar com o servidor."); } return response.json(); }
function vehicle(v: any): VehicleItem { const expenses = (v.expenses || []).map((e: any) => ({ ...e, partsCost: asNumber(e.partsCost), laborCost: asNumber(e.laborCost), amount: asNumber(e.amount), supplierName: e.supplier?.tradeName })); return { ...v, acquisitionPrice: asNumber(v.acquisitionPrice), fipePriceAtAcquisition: v.fipePriceAtAcquisition == null ? undefined : asNumber(v.fipePriceAtAcquisition), targetSalePrice: v.targetSalePrice == null ? undefined : asNumber(v.targetSalePrice), minimumSalePrice: v.minimumSalePrice == null ? undefined : asNumber(v.minimumSalePrice), mileageCurrent: asNumber(v.mileageCurrent), expenses, totalPartsCost: asNumber(v.totalPartsCost), totalLaborCost: asNumber(v.totalLaborCost), totalOtherCost: asNumber(v.totalOtherCost), totalExpensesCost: asNumber(v.breakdown?.totalExpensesCost), totalAccumulatedCost: asNumber(v.totalAccumulatedCost) }; }

export function GarageProvider({ children, initialSlug }: { children: React.ReactNode; initialSlug: string }) {
  const router = useRouter(); const [garage, setGarage] = useState(EMPTY_GARAGE); const [availableGarages, setAvailableGarages] = useState<GarageInfo[]>([]); const [vehicles, setVehicles] = useState<VehicleItem[]>([]); const [generalExpenses, setGeneralExpenses] = useState<GeneralExpenseItem[]>([]); const [sales, setSales] = useState<SaleItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { const memberships: any[] = await api("/api/v1/garages"); const garages = memberships.map(m => ({ ...m.garage, role: m.role })); setAvailableGarages(garages); const selected = garages.find(g => g.slug === initialSlug) || garages[0]; if (!selected) throw new Error("Você não possui uma garagem cadastrada."); setGarage(selected); const [vehiclesData, expensesData, salesData] = await Promise.all([api<any[]>(`/api/v1/garages/${selected.id}/vehicles`), api<any[]>(`/api/v1/garages/${selected.id}/expenses/general`), api<any[]>(`/api/v1/garages/${selected.id}/sales`)]); setVehicles(vehiclesData.map(vehicle)); setGeneralExpenses(expensesData.map(e => ({ ...e, amount: asNumber(e.amount), isPaid: e.paymentStatus === "PAGO" }))); setSales(salesData.map(s => ({ id: s.id, garageId: s.garageId, vehicleId: s.vehicleId, vehicleName: `${s.vehicle.brand} ${s.vehicle.model} ${s.vehicle.version || ""}`.trim(), plate: s.vehicle.plate, customerName: s.customer.name, saleDate: s.saleDate, finalSalePrice: asNumber(s.finalSalePrice), paymentMethod: s.paymentMethod, totalAccumulatedCost: asNumber(s.totalAccumulatedCost), grossProfit: asNumber(s.grossProfit), netProfit: asNumber(s.netProfit), hasTradeIn: !!s.tradeInVehicle, tradeInVehiclePlate: s.tradeInVehicle?.plate }))); } catch (cause: any) { if (cause.message === "Não autenticado.") router.replace("/login"); else setError(cause.message); } finally { setLoading(false); } }, [initialSlug, router]);
  useEffect(() => { void refresh(); }, [refresh]);
  const addVehicle = async (data: Partial<VehicleItem>) => { const result = await api<any>(`/api/v1/garages/${garage.id}/vehicles`, { method: "POST", body: JSON.stringify({ ...data, mileageIn: data.mileageCurrent, acquisitionDate: data.acquisitionDate || new Date().toISOString().slice(0, 10) }) }); await refresh(); return vehicle({ ...result, expenses: [] }); };
  const addVehicleExpense = async (vehicleId: string, data: { category: ExpenseCategory; description: string; partsCost: number; laborCost: number; otherCost?: number }) => { await api(`/api/v1/garages/${garage.id}/expenses/vehicle`, { method: "POST", body: JSON.stringify({ vehicleId, ...data, amount: data.partsCost + data.laborCost + (data.otherCost || 0), expenseDate: new Date().toISOString().slice(0, 10) }) }); await refresh(); };
  const updateVehicleStatus = async (vehicleId: string, status: VehicleStatus, notes?: string) => { await api(`/api/v1/garages/${garage.id}/vehicles/${vehicleId}/status`, { method: "PATCH", body: JSON.stringify({ status, notes }) }); await refresh(); };
  const addGeneralExpense = async (data: Omit<GeneralExpenseItem, "id" | "garageId" | "isPaid">) => { await api(`/api/v1/garages/${garage.id}/expenses/general`, { method: "POST", body: JSON.stringify({ ...data, paymentStatus: "PENDENTE" }) }); await refresh(); };
  const sellVehicle = async (vehicleId: string, data: SaleInput) => { const customer = await api<any>(`/api/v1/garages/${garage.id}/customers`, { method: "POST", body: JSON.stringify({ name: data.customerName, documentCpfCnpj: data.customerDocument, phone: data.customerPhone }) }); const tradeInVehicle = data.tradeIn ? { plate: data.tradeIn.plate, brand: data.tradeIn.brand, model: data.tradeIn.model, yearManufacture: data.tradeIn.yearManufacture, yearModel: data.tradeIn.yearModel, color: data.tradeIn.color, mileageIn: data.tradeIn.mileage, agreedTradeValue: data.tradeIn.agreedValue, notes: data.tradeIn.version } : undefined; await api(`/api/v1/garages/${garage.id}/sales`, { method: "POST", body: JSON.stringify({ vehicleId, customerId: customer.id, saleDate: new Date().toISOString().slice(0, 10), finalSalePrice: data.finalSalePrice, paymentMethod: data.paymentMethod, cashAmount: Math.max(0, data.finalSalePrice - (data.tradeIn?.agreedValue || 0)), salesCommissionAmount: data.salesCommission || 0, taxAmount: 0, otherDeductions: 0, tradeInVehicle, notes: data.notes }) }); await refresh(); };
  return <GarageContext.Provider value={{ garage, availableGarages, vehicles, generalExpenses, sales, loading, error, switchGarage: slug => router.push(`/${slug}`), refresh, addVehicle, addVehicleExpense, updateVehicleStatus, sellVehicle, addGeneralExpense }}>{children}</GarageContext.Provider>;
}
export function useGarage() { const context = useContext(GarageContext); if (!context) throw new Error("useGarage must be used within a GarageProvider"); return context; }
